In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [7]:
credits.shape

(4803, 4)

In [8]:
movies.shape

(4803, 20)

In [9]:
movies = movies.merge(credits, on='title')

In [10]:
movies.shape

(4809, 23)

In [11]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [12]:
#important columns to keep

# genres, id, keywords, title, overview, cast, crew

In [13]:
movies = movies[['movie_id', 'title','genres', 'overview', 'keywords', 'cast', 'crew']]

In [14]:
movies.head(2)

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [15]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   genres    4809 non-null   object
 3   overview  4806 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [16]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
overview    3
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
movies.dropna(inplace=True)

In [18]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
overview    0
keywords    0
cast        0
crew        0
dtype: int64

In [19]:
movies.duplicated().sum()

0

In [20]:
movies.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [21]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

#required format

# ['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [22]:
import ast

ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [23]:
def convert(data):
    lst = []
    for i in ast.literal_eval(data):
        lst.append(i['name'])
    return lst

In [24]:
movies['genres'] = movies['genres'].apply(convert)

In [25]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
movies.iloc[0]['keywords']

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [27]:
# Changing the format to list of keywords
# from
# '[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'
#  to
# ['culture clash', 'future', 'space war', 'space colony','society', 'space travel', 'futuristic', 'romance', 'space', 'alien',
#  'tribe',
#  'alien planet',
#  'cgi',
#  'marine',
#  'soldier',
#  'battle',
#  'love affair',
#  'anti war',
#  'power relations',
#  'mind and soul',
#  '3d']

In [28]:
movies['keywords'] = movies['keywords'].apply(convert)

In [29]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
movies.iloc[0]['cast']

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [31]:
def convert2 (data):
    lst = []
    data = ast.literal_eval(data)
    count = 0
    for i in data:
        if count != 10:
            count += 1
            lst.append(i['name'])
        else:
            break

    return lst

In [32]:
movies['cast'] = movies['cast'].apply(convert2)

In [33]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [34]:
# Fetching director name from crew

In [35]:
def get_director(data):
    lst = []
    data = ast.literal_eval(data)
    for i in data:
        if(i['job'] == 'Director'):
            lst.append(i['name'])
    return lst

In [36]:
movies['crew'] = movies['crew'].apply(get_director)

In [37]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [38]:
movies['genre'] = movies['genres'].apply(lambda x : [i.replace(' ', '_') for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x : [i.replace(' ', '_') for i in x])
movies['cast'] = movies['cast'].apply(lambda x : [i.replace(' ', '_') for i in x])
movies['crew'] = movies['crew'].apply(lambda x : [i.replace(' ', '_') for i in x])

In [39]:
movies['overview'] = movies['overview'].apply(lambda x : x.split(' '))

In [40]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew,genre
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[culture_clash, future, space_war, space_colon...","[Sam_Worthington, Zoe_Saldana, Sigourney_Weave...",[James_Cameron],"[Action, Adventure, Fantasy, Science_Fiction]"
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug_abuse, exotic_island, east_india_...","[Johnny_Depp, Orlando_Bloom, Keira_Knightley, ...",[Gore_Verbinski],"[Adventure, Fantasy, Action]"
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, based_on_novel, secret_agent, sequel, mi...","[Daniel_Craig, Christoph_Waltz, Léa_Seydoux, R...",[Sam_Mendes],"[Action, Adventure, Crime]"
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dc_comics, crime_fighter, terrorist, secret_i...","[Christian_Bale, Michael_Caine, Gary_Oldman, A...",[Christopher_Nolan],"[Action, Crime, Drama, Thriller]"
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[based_on_novel, mars, medallion, space_travel...","[Taylor_Kitsch, Lynn_Collins, Samantha_Morton,...",[Andrew_Stanton],"[Action, Adventure, Science_Fiction]"

In [41]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [42]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew,genre,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[culture_clash, future, space_war, space_colon...","[Sam_Worthington, Zoe_Saldana, Sigourney_Weave...",[James_Cameron],"[Action, Adventure, Fantasy, Science_Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug_abuse, exotic_island, east_india_...","[Johnny_Depp, Orlando_Bloom, Keira_Knightley, ...",[Gore_Verbinski],"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, based_on_novel, secret_agent, sequel, mi...","[Daniel_Craig, Christoph_Waltz, Léa_Seydoux, R...",[Sam_Mendes],"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dc_comics, crime_fighter, terrorist, secret_i...","[Christian_Bale, Michael_Caine, Gary_Oldman, A...",[Christopher_Nolan],"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[based_on_novel, mars, medallion, space_travel...","[Taylor_Kitsch, Lynn_Collins, Samantha_Morton,...",[Andrew_Stanton],"[Action, Adventure, Science_Fiction]","[John, Carter, is, a, war-weary,, former, mili..."

In [43]:
new_df = movies[['movie_id', 'title', 'tags']]

In [44]:
new_df['tags'] = new_df['tags'].str.join(' ')

C:\Users\SANSKAR\AppData\Local\Temp\ipykernel_24532\3998945911.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].str.join(' ')

In [45]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [46]:
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

C:\Users\SANSKAR\AppData\Local\Temp\ipykernel_24532\3998171751.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

In [47]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

now we have to convert the tags from string to vectors.
for this I am using text vectorisation. For this I am using scikit-learn library's CounterVectorizer method

CountVectorizor - It converts text documents into a numerical matrix based on word frequency, which helps in analyzing large collections of text data. This is done by counting how often each word appears in the document, giving a structured data format that can be used in machine learning models.

The return type of CountVectorizer is typically a sparse matrix of type "scipy.sparse.csr_matrix" by default. This matrix contains the frequency counts of each word in the document collection, with rows representing documents and columns representing words.

In [48]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [49]:
def stem(text):
    y = []
    for i in text.split(' '):
        y.append(ps.stem(i))
    return " ".join(y)

In [50]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\SANSKAR\AppData\Local\Temp\ipykernel_24532\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [52]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [53]:
# Now the problem with vectorization is that simiar meaning english words still gets separated
# for example, actor and actors means same thing but will treated as different words, similarly, actual&actually etc...
# To tackle this problem I will be using stemming
# What stemming does is that it will change similar words to a sing word 
# for example; dance, dancer, and dancing ----> dance, dance, dance

In [54]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [55]:
cv.get_feature_names_out().tolist()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1910',
 '1930',
 '1940',
 '1950',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1985',
 '1990',
 '19th',
 '19th_centuri',
 '20',
 '200',
 '20th',
 '24',
 '25',
 '30',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '_anderson',
 '_armi',
 '_b',
 '_brown',
 '_bush',
 '_d',
 '_dutton',
 '_emmet_walsh',
 '_fox',
 '_gainey',
 '_gary_gray',
 '_gr',
 '_hal',
 '_henson',
 '_j',
 '_jackson',
 '_johnson',
 '_jon',
 '_jr',
 '_le',
 '_lee_ermey',
 '_maci',
 '_mcginley',
 '_miller',
 '_murray_abraham',
 '_navi',
 '_nelson',
 '_night_shyamalan',
 '_o',
 '_reilli',
 '_simmon',
 '_smith',
 '_t',
 '_v',
 '_whit',
 '_wilson',
 'aaron',
 'aaron_eckhart',
 'aaron_taylor',
 'aasif_mandvi',
 'abandon',
 'abbie_cornish',
 'abduct',
 'abigail_breslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'action_hero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'adam',
 'adam_brodi',
 'adam_goldberg',
 'adam_sandl',
 'adam_scott',
 'adapt',
 'add',
 'addict',
 'adewale_akinnuoye',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrien_brodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'african_american',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'agbaj',
 'age',
 'age_differ',
 'agency',
 'agenda',
 'agent',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidan_quinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplane_crash',
 'airport',
 'aka',
 'al',
 'al_pacino',
 'alabama',
 'alan',
 'alan_alda',
 'alan_arkin',
 'alan_cum',
 'alan_rickman',
 'alan_tudyk',
 'alaska',
 'albert',
 'albert_brook',
 'albert_finney',
 'alcohol',
 'alec_baldwin',
 'alessandro_nivola',
 'alex',
 'alex_kendrick',
 'alexa_penavega',
 'alexis_bledel',
 'alfre_woodard',
 'alfred_hitchcock',
 'alfred_molina',
 'ali',
 'ali_lart',
 'alic',
 'alice',
 'alice_braga',
 'alicia_witt',
 'alien',
 'alien_invas',
 'alien_life',
 'alik',
 'alison_lohman',
 'aliv',
 'alive',
 'allen',
 'allen_covert',
 'alli',
 'allianc',
 'allison_janney',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyson_hannigan',
 'alzheimer',
 'amanda',
 'amanda_peet',
 'amanda_seyfri',
 'amateur',
 'amaz',
 'ambassador',
 'amber_heard',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'america_ferrera',
 'american',
 'american_abroad',
 'american_footbal',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusement_park',
 'amy',
 'amy_adam',
 'amy_poehl',
 'amy_ryan',
 'amy_sedari',
 'amy_smart',
 'analyst',
 'anarchic_comedi',
 'ancient',
 'ancient_rom',
 'ancient_world',
 'anderson',
 'andi',
 'andie_macdowel',
 'andre_braugh',
 'andrea_martin',
 'andrew',
 'android',
 'andy',
 'andy_dick',
 'andy_garcía',
 'andy_richt',
 'andy_samberg',
 'andy_serki',
 'ang_le',
 'angel',
 'angela_bassett',
 'angeles',
 'angelina_joli',
 'angelo',
 'anger',
 'angri',
 'ani',
 'anim',
 'animal_attack',
 'animal_horror',
 'animals',
 'anjelica_huston',
 'ann',
 'ann_dowd',
 'anna',
 'anna_fari',
 'anna_kendrick',
 'anna_paquin',
 'annasophia_robb',
 'anne',
 'anne_bancroft',
 'anne_hathaway',
 'anne_hech',
 'anne_moss',
 'annette_ben',
 'anni',
 'annie',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthony_anderson',
 'anthony_hopkin',
 'anthony_macki',
 'anthropomorph',
 'anti',
 'anti_hero',
 'anton_yelchin',
 'antonio_bandera',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'arms_deal',
 'army',
 'arnold',
 'arnold_schwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artificial_intellig',
 'artist',
 'ash',
 'ashley',
 'ashley_judd',
 'ashton_kutch',
 'asia',
 'asid',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atomic_bomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'bank_robb',
 'bank_robberi',
 'banker',
 'bar',
 'barbra_streisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barry_levinson',
 'barry_pepp',
 'bas',
 'base',
 'basebal',
 'based_on_comic_book',
 'based_on_graphic_novel',
 'based_on_novel',
 'based_on_play',
 'based_on_stage_mus',
 'based_on_true_ev',
 'based_on_true_stori',
 'based_on_tv_seri',
 'based_on_video_gam',
 'based_on_young_adult_novel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautiful_woman',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'becoming_an_adult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'ben_affleck',
 'ben_chaplin',
 'ben_fost',
 'ben_kingsley',
 'ben_mendelsohn',
 'ben_stil',
 'ben_whishaw',
 'bend',
 'benedict_cumberbatch',
 'benicio_del_toro',
 'benjamin',
 'benjamin_bratt',
 'bennett',
 'bent',
 'berlin',
 'bernard_le',
 'bernie_mac',
 'best',
 'best_friend',
 'bet',
 'beth',
 'beth_grant',
 'betray',
 'bette_midl',
 'better',
 'betti',
 'beverli',
 'beverly_d',
 'bibl',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'bill_cobb',
 'bill_had',
 'bill_moseley',
 'bill_murray',
 'bill_nighi',
 'bill_nunn',
 'bill_paxton',
 'bill_pullman',
 'billi',
 'billionair',
 'billy_bob_thornton',
 'billy_burk',
 'billy_connolli',
 'billy_crudup',
 'billy_cryst',
 'billy_dee_william',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'black_mag',
 'black_peopl',
 'blackmail',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'blood_splatt',
 'bloodi',
 'bloodthirsti',
 'blow',
 'blue',
 'blythe_dann',
 'board',
 'boat',
 'bob',
 'bob_balaban',
 'bob_gunton',
 'bob_hoskin',
 'bobbi',
 'bobby_cannaval',
 'bobby_farrelli',
 'bodi',
 'body',
 'bodyguard',
 'bokeem_woodbin',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonnie_hunt',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'bound',
 'bounti',
 'bounty_hunt',
 'box',
 'boxer',
 'boy',
 'boyd_holbrook',
 'boyfriend',
 'boys',
 'brad_dourif',
 'brad_garrett',
 'brad_pitt',
 'bradley_coop',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breckin_mey',
 'breed',
 'brendan_fras',
 'brendan_gleeson',
 'brent',
 'brett_ratn',
 'brian',
 'brian_cox',
 'brian_de_palma',
 'brian_dennehi',
 'brian_j',
 'brian_van_holt',
 'bride',
 'bridesmaid',
 'bridg',
 'bridget_fonda',
 'bridget_moynahan',
 'bridgette_wilson',
 'brie_larson',
 'brief',
 'brien',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'british_secret_servic',
 'brittany_murphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brothel',
 'brother',
 'brother_brother_relationship',
 'brother_sister_relationship',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruce_campbel',
 'bruce_dern',
 'bruce_greenwood',
 'bruce_mcgil',
 'bruce_willi',
 'brutal',
 'bryan_cranston',
 'bryan_sing',
 'bryce_dallas_howard',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddy_comedi',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'burt_reynold',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'buy',
 'byrn',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'callum_keith_renni',
 'calvin',
 'cam_gigandet',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'cameron_diaz',
 'camp',
 'campaign',
 'campbell',
 'campbell_scott',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'cannib',
 'capabl',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'car',
 'car_accid',
 'car_chas',
 'car_crash',
 'car_journey',
 'car_rac',
 'card',
 'care',
 'career',
 'caretak',
 'carey_mulligan',
 'caribbean',
 'carl',
 'carla_gugino',
 'carmen',
 'carmen_electra',
 'carol',
 'carol_kan',
 'carolina',
 'caroline_goodal',
 'carri',
 'carrie',
 'carrie_fish',
 'cartel',
 'carter',
 'cary',
 'cary_elw',
 'case',
 'casey_affleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cate_blanchett',
 'catherine_keen',
 'catherine_o',
 'catherine_zeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cave',
 'cedric_the_entertain',
 'celebr',
 'celia_imri',
 'celia_weston',
 'cell_phon',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'centuries',
 'century',
 'certain',
 'chad_michael_murray',
 'chain',
 'chainsaw',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changes',
 'channing_tatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charles_d',
 'charles_durn',
 'charles_s',
 'charli',
 'charlie',
 'charlie_sheen',
 'charlize_theron',
 'charlotte_rampl',
 'charlton_heston',
 'charm',
 'chart',
 'chase',
 'chazz_palminteri',
 'cheat',
 'check',
 'cheech_marin',
 'cheerlead',
 'chef',
 'chelcie_ross',
 'chemic',
 'cher',
 'chevy_chas',
 'chi_mcbrid',
 'chicago',
 'chicken',
 'chief',
 'child',
 'child_abus',
 'child_hero',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetel_ejiofor',
 'chloë_grace_moretz',
 'chloë_sevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chow_yun',
 'chri',
 'chris_columbu',
 'chris_coop',
 'chris_elliott',
 'chris_evan',
 'chris_hemsworth',
 'chris_kattan',
 'chris_klein',
 'chris_o',
 'chris_pin',
 'chris_pratt',
 'chris_rock',
 'christ',
 'christian',
 'christian_bal',
 'christian_slat',
 'christina_appleg',
 'christina_ricci',
 'christine_baranski',
 'christma',
 'christmas',
 'christmas_parti',
 'christoph',
 'christoph_waltz',
 'christopher_guest',
 'christopher_lambert',
 'christopher_le',
 'christopher_lloyd',
 'christopher_mcdonald',
 'christopher_meloni',
 'christopher_mintz',
 'christopher_plumm',
 'christopher_walken',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarán_hind',
 'cillian_murphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civil_war',
 'civilian',
 'claim',
 'clair',
 'claire_dan',
 'claire_forlani',
 'clan',
 'clancy_brown',
 'clark',
 'clark_gregg',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claude_van_damm',
 'clay',
 'clea_duval',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliff_curti',
 'clifton_collins_jr',
 'climat',
 'climb',
 'clint_eastwood',
 'clive_owen',
 'clock',
 'clone',
 'cloris_leachman',
 'close',
 'closer',
 'clown',
 'club',
 'clue',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'cold_war',
 'cole',
 'cole_haus',
 'colin',
 'colin_farrel',
 'colin_firth',
 'colin_hank',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colm_feor',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'coming_of_ag',
 'coming_out',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compton',
 'comput',
 'con_man',
 'conan',
 'concern',
 'concert',
 'condit',
 'confess',
 'confid',
 'conflict',
 'confront',
 'confus',
 'connect',
 'connel',
 'connie_nielsen',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 ...]

In [56]:
len(vectors)

4806

In [57]:
# So with the vectors we will have 4086 movies --> 4086 vectors in 5000 dimensional space
# So in higher dimension, ecuclidean distance fails
# Euclidean distance becomes less reliable in higher dimensions because of the curse of dimensionality. 
# In high-dimensional spaces, points tend to become equidistant, making it hard to distinguish between them based on distance alone. 
# This results in the distance losing its discriminative power as a measure of similarity.
# The curse of dimensionality refers to how adding more dimensions (features) to data can make it harder to analyze because the data becomes 
# sparse and distances between points become less meaningful.

# Hence we will use COSINE distance i.e. angle between two vectors. the less the angle the more the similarity

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
similarity = cosine_similarity(vectors)

In [60]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x : x[1])[1:11]

[(1214, 0.2944840695329241),
 (507, 0.2599480155948019),
 (539, 0.25007816164017765),
 (61, 0.24987801902176973),
 (2405, 0.24795914953354392),
 (1192, 0.24044523591131534),
 (2782, 0.24044523591131534),
 (1916, 0.23544080467400558),
 (4405, 0.2342606428329091),
 (3728, 0.2330745053742094)]

In [61]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x : x[1])[1:11]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [62]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Rockaway
Batman
10th & Wolf
Batman v Superman: Dawn of Justice
Defendor
Sexy Beast
Synecdoche, New York

In [63]:
import pickle

In [64]:
to_send = new_df.to_dict()

In [65]:
pickle.dump(to_send, open('movies.pkl', 'wb'))

In [66]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [67]:
to_send['title']

{0: 'Avatar',
 1: "Pirates of the Caribbean: At World's End",
 2: 'Spectre',
 3: 'The Dark Knight Rises',
 4: 'John Carter',
 5: 'Spider-Man 3',
 6: 'Tangled',
 7: 'Avengers: Age of Ultron',
 8: 'Harry Potter and the Half-Blood Prince',
 9: 'Batman v Superman: Dawn of Justice',
 10: 'Superman Returns',
 11: 'Quantum of Solace',
 12: "Pirates of the Caribbean: Dead Man's Chest",
 13: 'The Lone Ranger',
 14: 'Man of Steel',
 15: 'The Chronicles of Narnia: Prince Caspian',
 16: 'The Avengers',
 17: 'Pirates of the Caribbean: On Stranger Tides',
 18: 'Men in Black 3',
 19: 'The Hobbit: The Battle of the Five Armies',
 20: 'The Amazing Spider-Man',
 21: 'Robin Hood',
 22: 'The Hobbit: The Desolation of Smaug',
 23: 'The Golden Compass',
 24: 'King Kong',
 25: 'Titanic',
 26: 'Captain America: Civil War',
 27: 'Battleship',
 28: 'Jurassic World',
 29: 'Skyfall',
 30: 'Spider-Man 2',
 31: 'Iron Man 3',
 32: 'Alice in Wonderland',
 33: 'X-Men: The Last Stand',
 34: 'Monsters University',
 35: 'Transformers: Revenge of the Fallen',
 36: 'Transformers: Age of Extinction',
 37: 'Oz: The Great and Powerful',
 38: 'The Amazing Spider-Man 2',
 39: 'TRON: Legacy',
 40: 'Cars 2',
 41: 'Green Lantern',
 42: 'Toy Story 3',
 43: 'Terminator Salvation',
 44: 'Furious 7',
 45: 'World War Z',
 46: 'X-Men: Days of Future Past',
 47: 'Star Trek Into Darkness',
 48: 'Jack the Giant Slayer',
 49: 'The Great Gatsby',
 50: 'Prince of Persia: The Sands of Time',
 51: 'Pacific Rim',
 52: 'Transformers: Dark of the Moon',
 53: 'Indiana Jones and the Kingdom of the Crystal Skull',
 54: 'The Good Dinosaur',
 55: 'Brave',
 56: 'Star Trek Beyond',
 57: 'WALL·E',
 58: 'Rush Hour 3',
 59: '2012',
 60: 'A Christmas Carol',
 61: 'Jupiter Ascending',
 62: 'The Legend of Tarzan',
 63: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 64: 'X-Men: Apocalypse',
 65: 'The Dark Knight',
 66: 'Up',
 67: 'Monsters vs Aliens',
 68: 'Iron Man',
 69: 'Hugo',
 70: 'Wild Wild West',
 71: 'The Mummy: Tomb of the Dragon Emperor',
 72: 'Suicide Squad',
 73: 'Evan Almighty',
 74: 'Edge of Tomorrow',
 75: 'Waterworld',
 76: 'G.I. Joe: The Rise of Cobra',
 77: 'Inside Out',
 78: 'The Jungle Book',
 79: 'Iron Man 2',
 80: 'Snow White and the Huntsman',
 81: 'Maleficent',
 82: 'Dawn of the Planet of the Apes',
 83: 'The Lovers',
 84: '47 Ronin',
 85: 'Captain America: The Winter Soldier',
 86: 'Shrek Forever After',
 87: 'Tomorrowland',
 88: 'Big Hero 6',
 89: 'Wreck-It Ralph',
 90: 'The Polar Express',
 91: 'Independence Day: Resurgence',
 92: 'How to Train Your Dragon',
 93: 'Terminator 3: Rise of the Machines',
 94: 'Guardians of the Galaxy',
 95: 'Interstellar',
 96: 'Inception',
 97: 'Shin Godzilla',
 98: 'The Hobbit: An Unexpected Journey',
 99: 'The Fast and the Furious',
 100: 'The Curious Case of Benjamin Button',
 101: 'X-Men: First Class',
 102: 'The Hunger Games: Mockingjay - Part 2',
 103: "The Sorcerer's Apprentice",
 104: 'Poseidon',
 105: 'Alice Through the Looking Glass',
 106: 'Shrek the Third',
 107: 'Warcraft',
 108: 'Terminator Genisys',
 109: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 110: 'Pearl Harbor',
 111: 'Transformers',
 112: 'Alexander',
 113: 'Harry Potter and the Order of the Phoenix',
 114: 'Harry Potter and the Goblet of Fire',
 115: 'Hancock',
 116: 'I Am Legend',
 117: 'Charlie and the Chocolate Factory',
 118: 'Ratatouille',
 119: 'Batman Begins',
 120: 'Madagascar: Escape 2 Africa',
 121: 'Night at the Museum: Battle of the Smithsonian',
 122: 'X-Men Origins: Wolverine',
 123: 'The Matrix Revolutions',
 124: 'Frozen',
 125: 'The Matrix Reloaded',
 126: 'Thor: The Dark World',
 127: 'Mad Max: Fury Road',
 128: 'Angels & Demons',
 129: 'Thor',
 130: 'Bolt',
 131: 'G-Force',
 132: 'Wrath of the Titans',
 133: 'Dark Shadows',
 134: 'Mission: Impossible - Rogue Nation',
 135: 'The Wolfman',
 136: 'Bee Movie',
 137: 'Kung Fu Panda 2',
 138: 'The Last Airbender',
 139: 'Mission: Impossible III',
 140: 'White House Down',
 141: 'Mars Needs Moms',
 142: 'Flushed Away',
 143: 'Pan',
 144: 'Mr. Peabody & Sherman',
 145: 'Troy',
 146: "Madagascar 3: Europe's Most Wanted",
 147: 'Die Another Day',
 148: 'Ghostbusters',
 149: 'Armageddon',
 150: 'Men in Black II',
 151: 'Beowulf',
 152: 'Kung Fu Panda 3',
 153: 'Mission: Impossible - Ghost Protocol',
 154: 'Rise of the Guardians',
 155: 'Fun with Dick and Jane',
 156: 'The Last Samurai',
 157: 'Exodus: Gods and Kings',
 158: 'Star Trek',
 159: 'Spider-Man',
 160: 'How to Train Your Dragon 2',
 161: 'Gods of Egypt',
 162: 'Stealth',
 163: 'Watchmen',
 164: 'Lethal Weapon 4',
 165: 'Hulk',
 166: 'G.I. Joe: Retaliation',
 167: 'Sahara',
 168: 'Final Fantasy: The Spirits Within',
 169: 'Captain America: The First Avenger',
 170: 'The World Is Not Enough',
 171: 'Master and Commander: The Far Side of the World',
 172: 'The Twilight Saga: Breaking Dawn - Part 2',
 173: 'Happy Feet Two',
 174: 'The Incredible Hulk',
 175: 'The BFG',
 176: 'The Revenant',
 177: 'Turbo',
 178: 'Rango',
 179: 'Penguins of Madagascar',
 180: 'The Bourne Ultimatum',
 181: 'Kung Fu Panda',
 182: 'Ant-Man',
 183: 'The Hunger Games: Catching Fire',
 184: 'Home',
 185: 'War of the Worlds',
 186: 'Bad Boys II',
 187: 'Puss in Boots',
 188: 'Salt',
 189: 'Noah',
 190: 'The Adventures of Tintin',
 191: 'Harry Potter and the Prisoner of Azkaban',
 192: 'Australia',
 193: 'After Earth',
 194: 'Dinosaur',
 195: 'Night at the Museum: Secret of the Tomb',
 196: 'Megamind',
 197: "Harry Potter and the Philosopher's Stone",
 198: 'R.I.P.D.',
 199: 'Pirates of the Caribbean: The Curse of the Black Pearl',
 200: 'The Hunger Games: Mockingjay - Part 1',
 201: 'The Da Vinci Code',
 202: 'Rio 2',
 203: 'X2',
 204: 'Fast Five',
 205: 'Sherlock Holmes: A Game of Shadows',
 206: 'Clash of the Titans',
 207: 'Total Recall',
 208: 'The 13th Warrior',
 209: 'The Bourne Legacy',
 210: 'Batman & Robin',
 211: 'How the Grinch Stole Christmas',
 212: 'The Day After Tomorrow',
 213: 'Mission: Impossible II',
 214: 'The Perfect Storm',
 215: 'Fantastic 4: Rise of the Silver Surfer',
 216: 'Life of Pi',
 217: 'Ghost Rider',
 218: 'Jason Bourne',
 219: "Charlie's Angels: Full Throttle",
 220: 'Prometheus',
 221: 'Stuart Little 2',
 222: 'Elysium',
 223: 'The Chronicles of Riddick',
 224: 'RoboCop',
 225: 'Speed Racer',
 226: 'How Do You Know',
 227: 'Knight and Day',
 228: 'Oblivion',
 229: 'Star Wars: Episode III - Revenge of the Sith',
 230: 'Star Wars: Episode II - Attack of the Clones',
 231: 'Monsters, Inc.',
 232: 'The Wolverine',
 233: 'Star Wars: Episode I - The Phantom Menace',
 234: 'The Croods',
 235: 'Asterix at the Olympic Games',
 236: 'Windtalkers',
 237: "The Huntsman: Winter's War",
 238: 'Teenage Mutant Ninja Turtles',
 239: 'Gravity',
 240: "Dante's Peak",
 241: 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 242: 'Fantastic Four',
 243: 'Night at the Museum',
 244: 'San Andreas',
 245: 'Tomorrow Never Dies',
 246: 'The Patriot',
 247: "Ocean's Twelve",
 248: 'Mr. & Mrs. Smith',
 249: 'Insurgent',
 250: 'The Aviator',
 251: "Gulliver's Travels",
 252: 'The Green Hornet',
 253: '300: Rise of an Empire',
 254: 'The Smurfs',
 255: 'Home on the Range',
 256: 'Allegiant',
 257: 'Real Steel',
 258: 'The Smurfs 2',
 259: 'Speed 2: Cruise Control',
 260: "Ender's Game",
 261: 'Live Free or Die Hard',
 262: 'The Lord of the Rings: The Fellowship of the Ring',
 263: 'Around the World in 80 Days',
 264: 'Ali',
 265: 'The Cat in the Hat',
 266: 'I, Robot',
 267: 'Kingdom of Heaven',
 268: 'Stuart Little',
 269: 'The Princess and the Frog',
 270: 'The Martian',
 271: 'The Island',
 272: 'Town & Country',
 273: 'Gone in Sixty Seconds',
 274: 'Gladiator',
 275: 'Minority Report',
 276: 'Harry Potter and the Chamber of Secrets',
 277: 'Casino Royale',
 278: 'Planet of the Apes',
 279: 'Terminator 2: Judgment Day',
 280: 'Public Enemies',
 281: 'American Gangster',
 282: 'True Lies',
 283: 'The Taking of Pelham 1 2 3',
 284: 'Little Fockers',
 285: 'The Other Guys',
 286: 'Eraser',
 287: 'Django Unchained',
 288: 'The Hunchback of Notre Dame',
 289: "The Emperor's New Groove",
 290: 'The Expendables 2',
 291: 'National Treasure',
 292: 'Eragon',
 293: 'Where the Wild Things Are',
 294: 'Epic',
 295: 'The Tourist',
 296: 'End of Days',
 297: 'Blood Diamond',
 298: 'The Wolf of Wall Street',
 299: 'Batman Forever',
 300: 'Starship Troopers',
 301: 'Cloud Atlas',
 302: "Legend of the Guardians: The Owls of Ga'Hoole",
 303: 'Catwoman',
 304: 'Hercules',
 305: 'Treasure Planet',
 306: 'Land of the Lost',
 307: 'The Expendables 3',
 308: 'Point Break',
 309: 'Son of the Mask',
 310: 'In the Heart of the Sea',
 311: 'The Adventures of Pluto Nash',
 312: 'Green Zone',
 313: 'The Peanuts Movie',
 314: 'The Spanish Prisoner',
 315: 'The Mummy Returns',
 316: 'Gangs of New York',
 317: 'The Flowers of War',
 318: "Surf's Up",
 319: 'The Stepford Wives',
 320: 'Black Hawk Down',
 321: 'The Campaign',
 322: 'The Fifth Element',
 323: 'Sex and the City 2',
 324: 'The Road to El Dorado',
 325: 'Ice Age: Continental Drift',
 326: 'Cinderella',
 327: 'The Lovely Bones',
 328: 'Finding Nemo',
 329: 'The Lord of the Rings: The Return of the King',
 330: 'The Lord of the Rings: The Two Towers',
 331: 'Seventh Son',
 332: 'Lara Croft: Tomb Raider',
 333: 'Transcendence',
 334: 'Jurassic Park III',
 335: 'Rise of the Planet of the Apes',
 336: 'The Spiderwick Chronicles',
 337: 'A Good Day to Die Hard',
 338: 'The Alamo',
 339: 'The Incredibles',
 340: 'Cutthroat Island',
 341: 'Percy Jackson & the Olympians: The Lightning Thief',
 342: 'Men in Black',
 343: 'Toy Story 2',
 344: 'Unstoppable',
 345: 'Rush Hour 2',
 346: 'What Lies Beneath',
 347: 'Cloudy with a Chance of Meatballs',
 348: 'Ice Age: Dawn of the Dinosaurs',
 349: 'The Secret Life of Walter Mitty',
 350: "Charlie's Angels",
 351: 'The Departed',
 352: 'Mulan',
 353: 'Tropic Thunder',
 354: 'The Girl with the Dragon Tattoo',
 355: 'Die Hard: With a Vengeance',
 356: 'Sherlock Holmes',
 357: 'Ben-Hur',
 358: 'Atlantis: The Lost Empire',
 359: 'Alvin and the Chipmunks: The Road Chip',
 360: 'Valkyrie',
 361: "You Don't Mess with the Zohan",
 362: 'Pixels',
 363: 'A.I. Artificial Intelligence',
 364: 'The Haunted Mansion',
 365: 'Contact',
 366: 'Hollow Man',
 367: 'The Interpreter',
 368: 'Percy Jackson: Sea of Monsters',
 369: 'Lara Croft Tomb Raider: The Cradle of Life',
 370: 'Now You See Me 2',
 371: 'The Saint',
 372: 'Spy Game',
 373: 'Mission to Mars',
 374: 'Rio',
 375: 'Bicentennial Man',
 376: 'Volcano',
 377: "The Devil's Own",
 378: 'K-19: The Widowmaker',
 379: 'Conan the Barbarian',
 380: 'Cinderella Man',
 381: 'The Nutcracker: The Untold Story',
 382: 'Seabiscuit',
 383: 'Twister',
 384: 'Cast Away',
 385: 'Happy Feet',
 386: 'The Bourne Supremacy',
 387: 'Air Force One',
 388: "Ocean's Eleven",
 389: 'The Three Musketeers',
 390: 'Hotel Transylvania',
 391: 'Enchanted',
 392: 'Safe House',
 393: '102 Dalmatians',
 394: 'Tower Heist',
 395: 'The Holiday',
 396: 'Enemy of the State',
 397: "It's Complicated",
 398: "Ocean's Thirteen",
 399: 'Open Season',
 400: 'Divergent',
 401: 'Enemy at the Gates',
 402: 'The Rundown',
 403: 'Last Action Hero',
 404: 'Memoirs of a Geisha',
 405: 'The Fast and the Furious: Tokyo Drift',
 406: 'Arthur Christmas',
 407: 'Meet Joe Black',
 408: 'Collateral Damage',
 409: 'All That Jazz',
 410: 'Mirror Mirror',
 411: 'Scott Pilgrim vs. the World',
 412: 'The Core',
 413: 'Nutty Professor II: The Klumps',
 414: 'Scooby-Doo',
 415: 'Dredd',
 416: 'Click',
 417: 'Creepshow',
 418: 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 419: 'Jumper',
 420: 'Hellboy II: The Golden Army',
 421: 'Zodiac',
 422: 'The 6th Day',
 423: 'Bruce Almighty',
 424: 'The Expendables',
 425: 'Mission: Impossible',
 426: 'The Hunger Games',
 427: 'The Hangover Part II',
 428: 'Batman Returns',
 429: 'Over the Hedge',
 430: 'Lilo & Stitch',
 431: "Charlotte's Web",
 432: 'Deep Impact',
 433: 'RED 2',
 434: 'The Longest Yard',
 435: 'Alvin and the Chipmunks: Chipwrecked',
 436: 'Grown Ups 2',
 437: 'Get Smart',
 438: "Something's Gotta Give",
 439: 'Shutter Island',
 440: 'Four Christmases',
 441: 'Robots',
 442: 'Face/Off',
 443: 'Bedtime Stories',
 444: 'Road to Perdition',
 445: 'Just Go with It',
 446: 'Con Air',
 447: 'Eagle Eye',
 448: 'Cold Mountain',
 449: 'The Book of Eli',
 450: 'Flubber',
 451: 'The Haunting',
 452: 'Space Jam',
 453: 'The Pink Panther',
 454: 'The Day the Earth Stood Still',
 455: 'Conspiracy Theory',
 456: 'Fury',
 457: 'Six Days Seven Nights',
 458: 'Yogi Bear',
 459: 'Spirit: Stallion of the Cimarron',
 460: 'Zookeeper',
 461: 'Lost in Space',
 462: 'The Manchurian Candidate',
 463: 'Déjà Vu',
 464: 'Hotel Transylvania 2',
 465: 'Fantasia 2000',
 466: 'The Time Machine',
 467: 'Mighty Joe Young',
 468: 'Swordfish',
 469: 'The Legend of Zorro',
 470: 'What Dreams May Come',
 471: 'Little Nicky',
 472: 'The Brothers Grimm',
 473: 'Mars Attacks!',
 474: 'Evolution',
 475: 'The Edge',
 476: 'Surrogates',
 477: 'Thirteen Days',
 478: 'Daylight',
 479: 'Walking With Dinosaurs',
 480: 'Battlefield Earth',
 481: 'Looney Tunes: Back in Action',
 482: 'Nine',
 483: 'Timeline',
 484: 'The Postman',
 485: 'Babe: Pig in the City',
 486: 'The Last Witch Hunter',
 487: 'Red Planet',
 488: 'Arthur and the Invisibles',
 489: 'Oceans',
 490: 'A Sound of Thunder',
 491: 'Pompeii',
 492: 'Top Cat Begins',
 493: 'A Beautiful Mind',
 494: 'The Lion King',
 495: 'Journey 2: The Mysterious Island',
 496: 'Cloudy with a Chance of Meatballs 2',
 497: 'Red Dragon',
 498: 'Hidalgo',
 499: 'Jack and Jill',
 500: '2 Fast 2 Furious',
 501: 'The Little Prince',
 502: 'The Invasion',
 503: 'The Adventures of Rocky & Bullwinkle',
 504: 'The Secret Life of Pets',
 505: 'The League of Extraordinary Gentlemen',
 506: 'Despicable Me 2',
 507: 'Independence Day',
 508: 'The Lost World: Jurassic Park',
 509: 'Madagascar',
 510: 'Children of Men',
 511: 'X-Men',
 512: 'Wanted',
 513: 'The Rock',
 514: 'Ice Age: The Meltdown',
 515: '50 First Dates',
 516: 'Hairspray',
 517: 'Exorcist: The Beginning',
 518: 'Inspector Gadget',
 519: 'Now You See Me',
 520: 'Grown Ups',
 521: 'The Terminal',
 522: 'Hotel for Dogs',
 523: 'Vertical Limit',
 524: "Charlie Wilson's War",
 525: 'Shark Tale',
 526: 'Dreamgirls',
 527: 'Be Cool',
 528: 'Munich',
 529: 'Tears of the Sun',
 530: 'Killers',
 531: 'The Man from U.N.C.L.E.',
 532: 'Spanglish',
 533: 'Monster House',
 534: 'Bandits',
 535: 'First Knight',
 536: 'Anna and the King',
 537: 'Immortals',
 538: 'Hostage',
 539: 'Titan A.E.',
 540: 'Hollywood Homicide',
 541: 'Soldier',
 542: 'Carriers',
 543: 'Monkeybone',
 544: 'Flight of the Phoenix',
 545: 'Unbreakable',
 546: 'Minions',
 547: 'Sucker Punch',
 548: 'Snake Eyes',
 549: 'Sphere',
 550: 'The Angry Birds Movie',
 551: "Fool's Gold",
 552: 'Funny People',
 553: 'The Kingdom',
 554: 'Talladega Nights: The Ballad of Ricky Bobby',
 555: 'Dr. Dolittle 2',
 556: 'Braveheart',
 557: 'Jarhead',
 558: 'The Simpsons Movie',
 559: 'The Majestic',
 560: 'Driven',
 561: 'Two Brothers',
 562: 'The Village',
 563: 'Doctor Dolittle',
 564: 'Signs',
 565: 'Shrek 2',
 566: 'Cars',
 567: 'Runaway Bride',
 568: 'xXx',
 569: 'The SpongeBob Movie: Sponge Out of Water',
 570: 'Ransom',
 571: 'Inglourious Basterds',
 572: 'Hook',
 573: 'Die Hard 2',
 574: 'S.W.A.T.',
 575: 'Vanilla Sky',
 576: 'Lady in the Water',
 577: 'AVP: Alien vs. Predator',
 578: 'Alvin and the Chipmunks: The Squeakquel',
 579: 'We Were Soldiers',
 580: 'Olympus Has Fallen',
 581: 'Star Trek: Insurrection',
 582: 'Battle: Los Angeles',
 583: 'Big Fish',
 584: 'Wolf',
 585: 'War Horse',
 586: 'The Monuments Men',
 587: 'The Abyss',
 588: 'Wall Street: Money Never Sleeps',
 589: 'Dracula Untold',
 590: 'The Siege',
 591: 'Stardust',
 592: 'Seven Years in Tibet',
 593: 'The Dilemma',
 594: 'Bad Company',
 595: 'Doom',
 596: 'I Spy',
 597: 'Underworld: Awakening',
 598: 'Rock of Ages',
 599: "Hart's War",
 600: 'Killer Elite',
 601: 'Rollerball',
 602: 'Ballistic: Ecks vs. Sever',
 603: 'Hard Rain',
 604: 'Osmosis Jones',
 605: "Legends of Oz: Dorothy's Return",
 606: 'Blackhat',
 607: 'Sky Captain and the World of Tomorrow',
 608: 'Basic Instinct 2',
 609: 'Escape Plan',
 610: 'The Legend of Hercules',
 611: 'The Sum of All Fears',
 612: 'The Twilight Saga: Eclipse',
 613: 'The Score',
 614: 'Despicable Me',
 615: 'Money Train',
 616: 'Ted 2',
 617: 'Agora',
 618: 'Mystery Men',
 619: 'Hall Pass',
 620: 'The Insider',
 621: 'The Finest Hours',
 622: 'Body of Lies',
 623: 'Dinner for Schmucks',
 624: 'Abraham Lincoln: Vampire Hunter',
 625: 'Entrapment',
 626: 'The X Files',
 627: 'The Last Legion',
 628: 'Saving Private Ryan',
 629: 'Need for Speed',
 630: 'What Women Want',
 631: 'Ice Age',
 632: 'Dreamcatcher',
 633: 'Lincoln',
 634: 'The Matrix',
 635: 'Apollo 13',
 636: 'The Santa Clause 2',
 637: 'Les Misérables',
 638: "You've Got Mail",
 639: 'Step Brothers',
 640: 'The Mask of Zorro',
 641: 'Due Date',
 642: 'Unbroken',
 643: 'Space Cowboys',
 644: 'Cliffhanger',
 645: 'Broken Arrow',
 646: 'The Kid',
 647: 'World Trade Center',
 648: 'Mona Lisa Smile',
 649: 'The Dictator',
 650: 'Eyes Wide Shut',
 651: 'Annie',
 652: 'Focus',
 653: 'This Means War',
 654: 'Blade: Trinity',
 655: 'Red Dawn',
 656: 'Primary Colors',
 657: 'Resident Evil: Retribution',
 658: 'Death Race',
 659: 'The Long Kiss Goodnight',
 660: 'Proof of Life',
 661: 'Zathura: A Space Adventure',
 662: 'Fight Club',
 663: 'We Are Marshall',
 664: 'Hudson Hawk',
 665: 'Lucky Numbers',
 666: 'I, Frankenstein',
 667: 'Oliver Twist',
 668: 'Elektra',
 669: 'Sin City: A Dame to Kill For',
 670: 'Random Hearts',
 671: 'Everest',
 672: 'Perfume: The Story of a Murderer',
 673: 'Austin Powers in Goldmember',
 674: 'Astro Boy',
 675: 'Jurassic Park',
 676: 'Wyatt Earp',
 677: 'Clear and Present Danger',
 678: 'Dragon Blade',
 679: 'Little Man',
 680: 'U-571',
 681: 'The American President',
 682: 'The Love Guru',
 683: '3000 Miles to Graceland',
 684: 'The Hateful Eight',
 685: 'Blades of Glory',
 686: 'Hop',
 687: '300',
 688: 'Meet the Fockers',
 689: 'Marley & Me',
 690: 'The Green Mile',
 691: 'Wild Hogs',
 692: 'Chicken Little',
 693: 'Gone Girl',
 694: 'The Bourne Identity',
 695: 'GoldenEye',
 696: "The General's Daughter",
 697: 'The Truman Show',
 698: 'The Prince of Egypt',
 699: 'Daddy Day Care',
 700: '2 Guns',
 701: 'Cats & Dogs',
 702: 'The Italian Job',
 703: 'Two Weeks Notice',
 704: 'Antz',
 705: 'Couples Retreat',
 706: 'Days of Thunder',
 707: 'Cheaper by the Dozen 2',
 708: 'Maze Runner: The Scorch Trials',
 709: 'Eat Pray Love',
 710: 'The Family Man',
 711: 'RED',
 712: 'Any Given Sunday',
 713: 'The Horse Whisperer',
 714: 'Collateral',
 715: 'The Scorpion King',
 716: 'Ladder 49',
 717: 'Jack Reacher',
 718: 'Deep Blue Sea',
 719: 'This Is It',
 720: 'Contagion',
 721: 'Kangaroo Jack',
 722: 'Coraline',
 723: 'The Happening',
 724: 'Man on Fire',
 725: 'The Shaggy Dog',
 726: 'Starsky & Hutch',
 727: 'Jingle All the Way',
 728: 'Hellboy',
 729: 'A Civil Action',
 730: 'ParaNorman',
 731: 'The Jackal',
 732: 'Paycheck',
 733: 'Up Close & Personal',
 734: 'The Tale of Despereaux',
 735: 'The Tuxedo',
 736: 'Under Siege 2: Dark Territory',
 737: 'Jack Ryan: Shadow Recruit',
 738: 'Joy',
 739: 'London Has Fallen',
 740: 'Alien: Resurrection',
 741: 'Shooter',
 742: 'The Boxtrolls',
 743: 'Practical Magic',
 744: 'The Lego Movie',
 745: 'Miss Congeniality 2: Armed and Fabulous',
 746: 'Reign of Fire',
 747: 'Gangster Squad',
 748: 'Year One',
 749: 'Invictus',
 750: 'State of Play',
 751: 'Duplicity',
 752: 'My Favorite Martian',
 753: 'The Sentinel',
 754: 'Planet 51',
 755: 'Star Trek: Nemesis',
 756: 'Intolerable Cruelty',
 757: 'Trouble with the Curve',
 758: 'Edge of Darkness',
 759: 'The Relic',
 760: 'Analyze That',
 761: 'Righteous Kill',
 762: 'Mercury Rising',
 763: 'The Soloist',
 764: 'The Legend of Bagger Vance',

In [68]:
import requests

In [77]:
def fetch_poster(movie_id):
    url = "https://api.themoviedb.org/3/movie/{}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US".format(movie_id)
    data = requests.get(url)
    data = data.json()
    poster_path = data['poster_path']
    full_path = "https://image.tmdb.org/t/p/w500/" + poster_path
    return full_path

In [87]:
def recommend(movie):
    index = movies[movies['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])
    recommended_movie_names = []
    recommended_movie_posters = []
    for i in distances[1:6]:
        # fetch the movie poster
        movie_id = movies.iloc[i[0]].movie_id
        recommended_movie_posters.append(fetch_poster(movie_id))
        recommended_movie_names.append(movies.iloc[i[0]].title)

    return [recommended_movie_names,recommended_movie_posters]

recommended_movie_list = recommend('Batman Begins')

for i in range(len(recommended_movie_list[0])):
    print(recommended_movie_list[0][i])
    print(recommended_movie_list[1][i])

The Dark Knight
https://image.tmdb.org/t/p/w500//qJ2tW6WMUDux911r6m7haRef0WH.jpg
Batman
https://image.tmdb.org/t/p/w500//zzoPxWHnPa0eyfkMLgwbNvdEcVF.jpg
The Dark Knight Rises
https://image.tmdb.org/t/p/w500//hr0L2aueqlP2BYUblTTjmtn0hw4.jpg
Rockaway
https://image.tmdb.org/t/p/w500//9VlOskJuRF0rCqFzoZnfsBf4PC2.jpg
Batman
https://image.tmdb.org/t/p/w500//cij4dd21v2Rk2YtUQbV5kW69WB2.jpg

In [93]:
movies = pickle.load(open('movies.pkl', 'rb'))
movie_list = movies['title'].values
# movies['title'].values()

In [ ]:
index = movies[movies['title'] == 'Batman'].index[0]
distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])
recommended_movie_names = []
recommended_movie_posters = []
for i in distances[1:6]:
    # fetch the movie poster
    movie_id = movies.iloc[i[0]].movie_id
    recommended_movie_posters.append(fetch_poster(movie_id))
    recommended_movie_names.append(movies.iloc[i[0]].title)

NameError: name 'movie' is not defined